ip: "play.server.net"
name: "Server"
rewards:
  - "crate givekey %player% Vote 3"

claimed-message:
  - "&6&lServer &7\u25b6 &aYou have successfully voted on NameMC."

already-claimed-message:
  - "&6&lServer &7\u25b6 &cYou have already claimed your rewards."

command-message:
  - " "
  - "&6&lNameMC"
  - "&7Vote on the website below to claim your rewards"
  - "  &7\u25b6 &fhttps://namemc.com/server/play.server.net"
  - " "
  - "&7Once you have voted on the website, type /namemc again."

staff:
  has-voted: "&a%target% has voted on namemc"
  has-already-voted: "&c%target% has already voted on namemc"
  has-not-voted: "&c%target% has not voted on namemc"
  removed-vote: "&aYou have removed %target%'s vote"
  added-vote: "&aYou have force voted for %target%"

claimed:
